### ISSUE TITLE
Dice roll style removes roll results from chat cards

### ISSUE THREAD

**Issue by ronin-seven** [lizzard77/fvtt-embeds#1]
User came into FVTT discord complaining that roll results were missing from their chat cards, ex:
![image](https://github.com/lizzard77/fvtt-embeds/assets/47235915/df040655-d885-4a2d-877c-d84c2e0c7189)

We traced issue to this module's style definition:

`.message-content .dice-roll .dice-result .dice-total {
    display: none
}`

Removing this resolved the issue.

**Comment by lizzard77** [comment]
Hi - thanks for pointing out the issue. I'll remove the entire stylesheet, it's not really used at all. Sorry for the confusion.

**Comment by lizzard77** [comment]
fixed and released update to v0.2.3
