### ISSUE TITLE
Saved Credentials?

### ISSUE THREAD

**Issue by SabreRunner** [lizzard77/fvtt-embeds#2]
Is it possible to have saved credentials so I can use it to log in into my super secret Guide's Eyes Only Trello board with all the planning without making it public?

**Comment by lizzard77** [comment]
This is usually dependent on how Trello saves their authentication - I assume they are using a cookie that gets lost in the embedding from Foundry. I will play around with a private Trello board and report back whether or not that behaviour can be fixed.

**Comment by lizzard77** [comment]
Unfortunately, I see that Trello are blocking `iframe` embeds. This makes it impossible to embed Trello boards at all, I think.
