### ISSUE TITLE
V12 compatibility

### ISSUE THREAD

**Issue by TimorSol** [lizzard77/fvtt-embeds#3]
I believe this would not require any special editing of the code beyond a basic compatibility check. Journals have not been changed much in v12, but since the module states v11 only, it's not accessible anymore in Foundry instances that run on v12.

**Comment by lizzard77** [comment]
Thanks for pointing this out. I've updated the manifest for v12, but did no extensive testing beyond that. If you have the chance to test it, I'd be happy to receive any feedback.
