### ISSUE TITLE
In v12, it opens blank.

### ISSUE THREAD

**Issue by kagangtuya-star** [lizzard77/fvtt-embeds#4]
I am using v12.330 Foundry and fvtt embeds 0.3.
It cannot be displayed after embedding the page and no error message is reported in the console.
This doesn't seem to be a problem with the webpage, I've tested multiple webpages that do this.

![PixPin_2024-08-18_16-12-54](https://github.com/user-attachments/assets/c0dd7786-7c85-4e91-8406-dcb1a317a38b)

**Comment by lizzard77** [comment]
Thanks for pointing out the issue, I'll try to repro that using the site you've embedded

**Comment by lizzard77** [comment]
Fixed with v0.4, please update and let me know if anything doesn't work as expected!
